name: 18f eslint

on: [push]

jobs:
  lint:
    name: 18F ESLint
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: 18f/18f-eslint-action@ada088f
        with:
          working-directory: src
