name: 18f eslint

on: [push]

jobs:
  lint:
    name: 18F ESLint
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: 18f/18f-eslint-action@7f73ad6
        with:
          working-directory: src
          only-changed: "true"
